#!/bin/bash
create_virtuelle_machine(){
echo "create vm succseeful"


	
}
check_passwd(){

echo checkpasswd
}
normal_commande()
{
	if [ "$1" == "q" ]
	then
		exit 1
	elif [ "$1" == "connect" ]
	then
		state=2
		return 0
	elif [ "$1" == "su" ]
	then	state=3
			return 0
	elif [ "$1" == "test" ]
	then echo "test"
		return 0
	else 
		return 1
	fi
	#echo $1 normal_commande
	return 0

}
special_commande(){
echo $1 special_commande
return 0

}
run(){
while [ $state -eq 1 ]
do
	read -p "$1" commande
	normal_commande $commande
	if [ $? -eq 1 ] 
	then
		if [ "$2" == "-s" ]
		then
				special_commande $commande
		else
			echo "pleas entre the right commande"
		fi
	fi
done

}
run_commande(){
if [ "$mode" == "-connect" ]
then
	a=$#
	#check_argument
	if [ $# != 3 ]
	then 
		echo "wrong number of the arguments"
		exit 1
	fi
	#check_utilisateur||machine
	check_passwd
	#check password of the machine
	run "$machine@$user>" -n
#end of connection
elif [ "$mode" == "-admin" ]
then
	if [ $# != 1 ]
	then 
		echo "wrong number of the arguments"
		exit 1
	fi
	check_passwd
	#check password of root
	run "rvsh>" -s
#end of connection

else
	echo "please entre the right options"
fi
}
create_virtuelle_machine
flag=1
state=1
mode=$1
user=$2
machine=$3
while [ $flag -eq 1 ]
do
	if [ $state == 1 ]
	then
		run_commande $mode $user $machine
	elif [ $state == 2 ]
	then 
		read -p "entre the machine : " machine
		state=1
		run_commande $mode $user $machine
	elif [ $state == 3 ]
	then
		read -p "entre the user : " user
		state=1
		run_commande $mode $user $machine
		#if the user==root then run the admin
	fi
done


