#!/bin/bash
create_virtuelle_machine(){
	
	echo "create vm succseeful"

}
check_passwd(){

echo checkpasswd
}
normal_commande()
{
	if [ "$1" == "q" ]
	then
		exit 1
	elif [ "$1" == "connect" ]
	then
		state=2
		return 0
	elif [ "$1" == "su" ]
	then	state=3
			return 0
	elif [ "$1" == "test" ]
	then echo "test"
		return 0
	else 
		return 1
	fi
	#echo $1 normal_commande
	return 0

}
special_commande(){
	if [ "$1" == "host" ]
	then
		./outils/check_file ./rv/vms/$2
		if [ $? == 1 ]
		then
			echo "host exit"
		else
			mkdir ./rv/vms/$2
		fi
	elif [ "$1" == "users" ]
	then
		while read line
		do
			name=$(echo "$line" | cut -d ":" -f1)
			if [ "$2" == "$name" ]
			then
				echo "Error:user exit"
				return 0
			fi
		done<./rv/userlist
		echo "set the password:"
		read passwd
		echo $2:$passwd >> ./rv/userlist
		echo "add user successfully"
	else
		echo "no command found"
	fi
	return 0
}
run(){
while [ $state -eq 1 ]
do
	read -p "$1" commande
	normal_commande $commande
	if [ $? -eq 1 ] 
	then
		if [ "$2" == "-s" ]
		then
				special_commande $commande
		else
			echo "pleas entre the right commande"
		fi
	fi
done

}
run_commande(){
if [ "$mode" == "-connect" ]
then
	a=$#
	#check_argument
	if [ $# != 3 ]
	then 
		echo "wrong number of the arguments"
		exit 1
	fi
	#check_utilisateur||machine
	./outils/check_passwd $user ./rv/userlist
	#check password of the machine
	run "$user@$machine>" -n
#end of connection
elif [ "$mode" == "-admin" ]
then
	if [ $# != 1 ]
	then 
		echo "wrong number of the arguments"
		exit 1
	fi
	./outils/check_passwd admin ./rv/admin 
	#check password of root
	if [ $? == 0 ]
	then
		run "rvsh>" -s
	else
		exit 1
	fi
#end of connection

else
	echo "please entre the right options"
	exit 1
fi
}


###################################################


flag=1
state=1
mode=$1
user=$2
machine=$3
./outils/check_file ./rv/admin
if [ $? == 0 ]
then
	./outils/init_admin
fi

while [ $flag -eq 1 ]
do
	if [ $state == 1 ]
	then
		run_commande $mode $user $machine
	elif [ $state == 2 ]
	then 
		read -p "entre the machine : " machine
		state=1
		run_commande $mode $user $machine
	elif [ $state == 3 ]
	then
		read -p "entre the user : " user
		state=1
		run_commande $mode $user $machine
		#if the user==root then run the admin
	fi
done


