#!/bin/bash
#1 machine
#2 user
while [ 1 -eq 1 ]
do
	sleep 1
if [ 1 != $(cat ./rv/vms/$1/$2/message_new | wc -c) ]
then
cat ./rv/vms/$1/$2/message_new
cat ./rv/vms/$1/$2/message_new >> ./rv/vms/$1/$2/message_total
echo > ./rv/vms/$1/$2/message_new
fi
done
