#!/bin/bash
# 1 is the user name,2 is the file name
read -p "password:" password
while read line
do
	name=$(echo $line | cut -d ":" -f1)
	if [ $name == $1 ]
	then
		passwd=$(echo $line | cut -d ":" -f2)
		if [ $password == $passwd ]
		then
			exit 0
		else
			echo "wrong password"
			exit 1
		fi
	fi
done<$2
echo "user not found"
exit 1
