#!/bin/bash
# 1 is the user name 2 is the machine name 3 is the userid
a=$(ls ./rv/vms | grep $2)
if [ $? != 0 ]
then
	echo "no such virtuelle machine"
	exit 1
fi
a=$(ls ./rv/users | grep $1)
if [ $? != 0 ]
then
	echo "no such user "
	exit 1
fi
mkdir ./rv/vms/$2/$1
logtime=$(date)
echo "login: "$2 $1 $logtime >> ./rv/users/$1/log_info
echo "login: "$2 $1 $logtime >> ./rv/users/$1/login_info
echo $2 $logtime >> ./rv/online_users/$1
./outils/check_file ./rv/online_users
if [ $? == 1 ]
then
	echo $1 $2 $logtime >> ./rv/online_data
fi
echo "$3 $1 $2 $logtime" >> ./rv/online_users_id

