#!/bin/bash
# 1 is the user name,2 is the machine name 3 is the id
num=$(cat ./rv/online_users/$1/num_ter)
if [ $num == 0 ]
then
	rm -rf ./rv/vms/$2/$1
	rm -rf ./rv/online_users/$1
else
	echo $(($num-1))>./rv/online_users/$1/num_ter
fi
logtime=$(date)
echo "logout: "$2 $1 $logtime >> ./rv/users/$1/log_info
echo "logout: "$2 $1 $logtime >> ./rv/users/$1/logout_info
sed -i "/^$1/d" ./rv/online_data
